apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: Cr3ss1d4!Olim
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: user
  POSTGRES_NON_ROOT_PASSWORD: pass123